export default {
  INSURANCE_FETCH_SUCCEEDED: "INSURANCE_FETCH_SUCCEEDED",
  INSURANCE_FETCH_FAILED: "INSURANCE_FETCH_FAILED",
  INSURANCE_TYPE_CHANGED: "INSURANCE_TYPE_CHANGED",
  ACTTION_STATE_CHANGED: "ACTTION_STATE_CHANGED"
};
